- job:
    name: ansible-role-zuul-base
    parent: unittests
    pre-run: tests/playbooks/pre.yaml
    run: tests/playbooks/run.yaml
    post-run: tests/collect-logs.yaml
    roles:
      - zuul: windmill/ansible-role-zuul

# Testing for zuul_install_method: pip
- job:
    name: ansible-role-zuul
    parent: ansible-role-zuul-base

- job:
    name: ansible-role-zuul-ubuntu-bionic
    parent: ansible-role-zuul
    nodeset: ubuntu-bionic
    vars:
      zuul_pip_version: 3.19.1
      zuul_pip_name: zuul[mysql_reporter]

# Testing for zuul_install_method: git
- job:
    name: ansible-role-zuul-src
    parent: ansible-role-zuul-base
    required-projects:
      - name: zuul/zuul
    vars:
      zuul_git_update: false
      zuul_install_method: git

- job:
    name: ansible-role-zuul-src-ubuntu-bionic
    parent: ansible-role-zuul-src
    nodeset: ubuntu-bionic

- project:
    templates:
      - windmill-jobs-bionic
    check:
      jobs:
        - ansible-role-zuul-ubuntu-bionic
        - ansible-role-zuul-src-ubuntu-bionic:
            voting: false
        - tox-linters
    gate:
      jobs:
        - ansible-role-zuul-ubuntu-bionic
        - tox-linters
