---
- name: Define zuul_build_depends.
  set_fact:
    zuul_build_depends: "{{ __zuul_build_depends | list }}"
  when: zuul_build_depends is not defined

- include: install/debian.yaml
  when: ansible_os_family == 'Debian'

- include: install/redhat.yaml
  when: ansible_os_family == 'RedHat'

- include: install/git.yaml
  when: zuul_install_method == 'git'

- include: install/pip.yaml
  when: zuul_install_method == 'pip'
