---
- name: Copy systemd file into place for zuul-merger.
  copy:
    dest: /etc/systemd/system
    src: ../../files/zuul-merger.service

- name: Copy systemd file into place for zuul-server.
  copy:
    dest: /etc/systemd/system
    src: ../../files/zuul-server.service

- name: Copy sysconfig file into place.
  copy:
    dest: /etc/sysconfig/zuul
    src: ../../files/zuul.sysconfig

- name: Enable zuul-merger service.
  service:
    enabled: yes
    name: zuul-merger
    state: started

- name: Enable zuul-server service.
  service:
    enabled: yes
    name: zuul-server
    state: started
